### ISSUE TITLE
openCV projects - 404 error

### ISSUE THREAD

**Issue by sanketkhanwalkar** [jaredsburrows/OpenQuartz#5]
Both the links for openCV projects for glass, seem to be not accessible. Clicking on either links throws a file not found error. Please update the links. Thanks.

**Comment by jaredsburrows** [comment]
@sanketkhanwalkar The projects still exist here: https://github.com/jaredsburrows/OpenQuartz/tree/master/examples-old

I am still migrating the Eclipse projects to Android Studio and will update the links soon.

**Comment by jaredsburrows** [comment]
@sanketkhanwalkar Are you still seeing this problem?
