### ISSUE TITLE
Settings.apk not working.

### ISSUE THREAD

**Issue by DaMalo** [jaredsburrows/OpenQuartz#6]
I have an issue with the Settings.apk in the third-party directory. I installed it using the provided install.sh script. When I run the Settings.apk on glass using adb I get to the following screen:

![glassscreenshot](https://cloud.githubusercontent.com/assets/1702519/5863266/8966d368-a278-11e4-8b28-05377911ff42.png)

But from there no input is accepted, swiping does nothing and tapping the touchpad closes the settings.

Steps:
1. Install third party tools via the provided install.sh script
2. Run the Settings.apk using following command:
adb shell am start -a android.intent.action.MAIN -n com.android.settings/com.android.settings.Settings
3. The screen depicted in the image above appears but the menu can't be navigated using glass

Maybe you can help me sorting this out. Please tell me if you need further information to reproduce this issue.

Best regards,
Daniel

**Comment by jaredsburrows** [comment]
Thanks for the update. Possibly with the latest XE software this was disabled or prevented from changing the settings of the OS. Have you tried anything else?

Also, if you have it successfully installed and can intent to the app. Maybe there is another way to toggle those services?

**Comment by jaredsburrows** [comment]
@DaMalo Any update on your end?
